baseurl = "https://www.jointheresistance.io/"
title = "Join The Resistance"
languageCode = "en-us"
theme = "dimension"

[Permalinks]
	posts = "/:year/:month/:filename/"

[Params]
abouttext = "About Us"

title = "Join The Resistance"
description = "Tools for Instigators & Organizers"
logo = "fa-fire"
copyright = "2017 JoinTheResistance.io"


